<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-13</name>
   <tag></tag>
   <elementGuidId>8873a5bb-97f7-459e-8c85-eb611afe32b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ca610fd-0ab2-4b9c-bdc7-0bf87a9ab64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b07ba78c-5fe1-4bb2-a6f5-3c20c40bdb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-13</value>
      <webElementGuid>9715f6c1-c28c-41ef-829e-6acb2ccdc7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email!</value>
      <webElementGuid>5afa79c6-7f91-4643-8ccf-236664f7aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9311827-4504-4023-932d-e7d8305dd8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-13&quot;)</value>
      <webElementGuid>38399a66-7f11-486b-953b-55705ad6cb74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-13']</value>
      <webElementGuid>5cf9652f-98d0-421c-8b89-a3a88ff83272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>210d9862-1d72-4ffe-a393-c1a6477fa00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ace276fb-d4f3-4efe-afb3-bd649b2b16cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-13' and @placeholder = 'Enter your email!' and @type = 'text']</value>
      <webElementGuid>1cd50cfd-5da7-480d-9896-42ec60aacd42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
