<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-16</name>
   <tag></tag>
   <elementGuidId>ca2723a1-1dc4-4454-8e28-f4359248ab42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8759c75-c68c-40d9-bab1-018fe73898cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>941e392b-3898-48a9-bf29-03abe57ce694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-16</value>
      <webElementGuid>6bef235e-a566-490a-a0cc-d0c9c80ec1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password!</value>
      <webElementGuid>1ff59dd8-a6f0-4b12-94d2-ce83ae794f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>40c4cdfa-6241-4873-ac12-606dbba8d3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-16&quot;)</value>
      <webElementGuid>aa6ff479-9379-460a-b279-d201511db055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-16']</value>
      <webElementGuid>d7ff8ab7-ef2e-4080-a73b-b3a785b0fa17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>eafdb86a-559a-41a9-ad45-167216394904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>8767e7bc-5bd5-43b5-b474-bad3b408e398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-16' and @placeholder = 'Enter your password!' and @type = 'password']</value>
      <webElementGuid>6f79d4f4-ae54-4163-822c-d8a5aa39ae53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
