<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-13</name>
   <tag></tag>
   <elementGuidId>9de5b38d-43c4-45ba-8e7a-a265a9ce8a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c803072f-9f5b-471d-85da-f6f208b866da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>07bad770-5973-461f-ab08-ff5c2a25db76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-13</value>
      <webElementGuid>b1a53014-6b2b-4c94-af69-d523d9d4c0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email!</value>
      <webElementGuid>bea0b715-040a-467b-be9c-445b520a8459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>525c9f6b-7bbc-45de-a285-cd27b868d034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-13&quot;)</value>
      <webElementGuid>695aca11-f286-4a41-9163-93008e618d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-13']</value>
      <webElementGuid>0ec9fe44-1e1c-43f0-a1c3-34e0a8af8191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>c9f799ba-e483-4f11-9d59-fdde32b8fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1d53dca6-a21f-4f1d-ae8d-e2a2caff9701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-13' and @placeholder = 'Enter your email!' and @type = 'text']</value>
      <webElementGuid>4eb83d97-5424-47fa-91dc-9ff36f99e8b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
