<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paket Data_v-card v-card--link v-sheet _b0c0ab</name>
   <tag></tag>
   <elementGuidId>abe175f7-47f1-43f7-ab02-a1410dca38b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[4]/div/div/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aad15360-6c9e-4c6a-9183-044ed7dea8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb9ce4a6-fdfe-4c3f-9632-8509e834ac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-card v-card--link v-sheet theme--light light d-flex align-center flat card</value>
      <webElementGuid>cccd0e20-c91c-42f3-b865-c06eb2c527f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row row--dense&quot;]/div[@class=&quot;d-flex child-flex col&quot;]/div[@class=&quot;v-card v-sheet theme--light light align-center flat card&quot;]/div[@class=&quot;row row--dense&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 col-md-2 col-lg-1 col-xl-1 col-4&quot;]/div[@class=&quot;v-card v-card--link v-sheet theme--light light d-flex align-center flat card&quot;]</value>
      <webElementGuid>26825906-c472-4e69-973f-91e24af48844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>3760f6bd-9fc5-4305-a035-bad6e53111cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Data'])[2]/following::div[21]</value>
      <webElementGuid>f854c72f-8297-4519-9ccc-1b42aa810fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::div[28]</value>
      <webElementGuid>e1355ef6-8bdf-41fb-9009-5ebca9c72a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/preceding::div[12]</value>
      <webElementGuid>bd6393f2-777a-489a-91c3-6315858db0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div</value>
      <webElementGuid>e02ad280-2d5c-42cb-b066-5abfac97d868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
